### ISSUE TITLE
The string "--" is not permitted within comments

### ISSUE THREAD

**Issue by CosetteN** [sidorovich/jenkins_ci_config#1]
Hello!

Using your build.xml as a tutorial for my own ant for a Codeception in Jenkins project.

How do you resolve the "The string "--" is not permitted within comments." error that occurs when you have failonerror="true" in your exec string?

**Comment by sidorovich** [comment]
Where you got this error? Can you put full console log here?
I have no this error in my project.

**Comment by CosetteN** [comment]
I figured it out with some stackoverflow help.  Totally newbie (which I am) mistake.  I had gotten this working with multiple tests/targets.  Then commented out some when trying something new.  The section inside of  had some codeception commands.  That is what triggered this error.  

Hopefully this being here will help the next person out.
